---
- hosts: all
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: "Create document root"
      file:
        path: "{{ docroot }}"
        state: directory
        owner: www-data
        group: www-data
        mode: 0755
    - name: "Copy file index.html"
      copy:
        src: files/index.html
        dest: "{{ docroot }}"
        owner: www-data
        group: www-data
        mode: 0644
  roles:
    - { role: ansible-role-apache }
  