---
- hosts: all
  vars_files:
    - vars/main.yml
  pre_tasks:
    - file:
        path: "{{ docroot }}"
        state: directory
        mode: 0755
        owner: www-data
        group: www-data
  roles:
    - { role: ansible-role-apache }
  